services:
  - type: web
    name: phonecaseblazorserverapp
    docker:
      build:
        dockerfile: Dockerfile
      image: phonecaseblazorserverapp-image
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
